#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  web:
    resources:
      static-locations[0]: file:src/main/resources/static/
      static-locations[1]: classpath:/static/
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
        id.new_generator_mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/budgets
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  sql:
    init:
      mode: always
logging:
  level:
    web: debug
file:
  upload:
    location: ./src/main/resources/static/uploads
  template:
    location: ./src/main/resources/static/templates
